---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies NPM"
  become: true
  apt:
    name: "npm"
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: "pm2"
    global: yes

- name: Create directory if it doesn't already exist
  ansible.builtin.file:
      path: ~/web
      state: directory
      mode: 0755
  
- name: "copy files to new directory"
  copy:
    src: files/index.js
    dest: ~/web/index.js

- name: to start webserver
  command: pm2 start ~/web/index.js -f